apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-housing-app
spec:
  replicas: 1 # Starts with 1 container instance
  selector:
    matchLabels:
      app: housing-app
  template:
    metadata:
      labels:
        app: housing-app
    spec:
      containers:
      - name: housing-app
        image: housing-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
